### ISSUE TITLE
Some minor bugs in translation

### ISSUE THREAD

**Issue by Gaoyifei1011** [veler/DevToys#128]
Some minor bugs in translation
翻译中的一些小bug

在设置中的语言选择中，仅仅只是显示了“中文（中国）”这一项，这个翻译并不是太准确。因为在中文中分为简体中文和繁体中文，在中华人民共和国的管辖区域中，简体中文是中国大陆在使用，繁体中文是中国台湾省，中国香港特别行政区，中国澳门特别行政区这些地方在使用。希望能够细化一下，将“中文（中国）“修改为“简体中文（中华人民共和国）”或”简体中文（中国）“更为准确一些
In the language selection in the Settings, only "Chinese" is displayed, which is not quite accurate. Because Chinese is divided into simplified Chinese and traditional Chinese, simplified Chinese is used in mainland China under the jurisdiction of the People's Republic of China, while traditional Chinese is used in Taiwan Province of China, Hong Kong Special Administrative Region of China, and Macao Special Administrative Region of China. Hope to refine the "Chinese (China)" to "simplified Chinese (People's Republic of China)" or "simplified Chinese (China)" more accurate

**Comment by veler** [comment]
Hello,

Thank you for sharing this feedback.

Quick question: how is it displayed in the language settings of Windows?

I'm asking because I did not define `中文（中国）` by myself. In fact, I let the Windows API providing the name of the language in its native form is.
I do not speak Chinese, so my translation might not be correct: I think `中文（中国）`  means `Chinese (China)` in English, isn't it?

I can see in the debugger that the English name if `Chinese (Simplified, China)`.

![image](https://user-images.githubusercontent.com/3747805/147800329-e41aee7f-6bb0-4495-861e-4a22c193d863.png)

My interpretation of all this (but I can be wrong) is that in `Chinese (China)`, "China" refers to "mainland China". If that's correct, then `Chinese (China)` may implicitly mean "Simplified Chinese".

**Question:** is there any guidance or law that asks to use `Chinese (Simplified, China)` instead of `Chinese (China)`?

**Comment by Gaoyifei1011** [comment]
Thank you very much for your reply
非常感谢您的回信

The Add Language screen in Windows Settings looks like this. It clearly shows both simplified and traditional Chinese characters.
在Windows 设置中添加语言界面是这样显示的，它明显的显示了中文的简体和繁体说明。
![image](https://user-images.githubusercontent.com/49179966/147800812-5e5655eb-45a6-4a32-8693-69ba23effb3d.png)
其他的，这是在7zip和files这两个软件显示添加语言的选项
![屏幕截图 2021-12-31 110352](https://user-images.githubusercontent.com/49179966/147800852-5cdd496f-3b65-43bc-97f0-9123fae531a0.png)
![屏幕截图 2021-12-31 110442](https://user-images.githubusercontent.com/49179966/147800853-7306884d-4c1e-4370-9a34-74b9e01aeb51.png)

**Comment by veler** [comment]
Hi,
Thank you for these information! I will try to look at how 7zip and Files do and will apply a fix. :)

**Comment by veler** [comment]
Hi @Gaoyifei1011,
Is this better?

![image](https://user-images.githubusercontent.com/3747805/147835937-343ce6a5-f6fc-4b38-bc1b-cc0d4ecfc9ed.png)

**Comment by Gaoyifei1011** [comment]
非常抱歉，没有及时回复。您那时发给我的信息，北京时间是凌晨两点，抱歉。这样翻译就可以了，非常感谢您对简体中文细化翻译的支持。
I am very sorry for not replying in time. The message you sent me at that time, Beijing time is 2 am, sorry. This translation is ok. Thank you very much for your support of simplified Chinese translation.

**Comment by veler** [comment]
Hi,
No worries at all :-) 
Thank you for confirming!
Fo your information, the issue was that the folder where the Simplified Chinese translation was named "zh-CN", which corresponds to "Chinese (China)". Renaming this folder as "zh-Hans" fix the issue. :)

I will add the fix to the code base and will release an update in the next few days.

Have a wonderful day! Thank you again for your help :)

**Comment by veler** [comment]
https://github.com/veler/DevToys/commit/adaa1e22d4de2229d8f2d00b676e31fd2d91c17f

**Comment by Gaoyifei1011** [comment]
![image](https://user-images.githubusercontent.com/49179966/148798990-eec7b9e9-ce1b-4576-8126-86f112b82c9e.png)
上次忘记说了，在您添加了“中文（简体）”选项后，需要您做出一些修改。
语言选择菜单里包括“中文（中国）”和"中文（简体）"这两个选项。然而，这两个选项对应的语言都是一样的，两个选项发生了重复。而且”中文（中国）“实际上包含“中文（简体）”和“中文（繁体）”这两个内容，实际上并没有对应“中文（繁体）”的翻译，希望您能够解决一下这个问题。
I forgot to mention last time, after you added the "中文（简体）" option, you need to make some changes.
The language selection menu includes "中文（中国）" and "中文（简体）". However, both options correspond to the same language, and both options are duplicated. In addition, "中文（中国）" actually contains "中文（简体）" and "中文（繁体）", but there is no corresponding translation of "中文（繁体）". I hope you can solve this problem.

这是知乎上面给出的一些关于简体中文和繁体中文区别的一些回答
Here are some answers on Zhihu about the difference between simplified Chinese and traditional Chinese
https://zhuanlan.zhihu.com/p/96208556
https://zhuanlan.zhihu.com/p/35472331

知乎，类似于美国软件Quora。
Zhihu is similar to Quora

在您阅读了这些具体介绍后有助于您能够更好的了解简体中文和繁体中文的区别，由来，文化和历史。
After reading these detailed introductions, you will be able to better understand the differences between simplified Chinese and traditional Chinese, its origin, culture and history.
