### ISSUE TITLE
Change to a more appropriate license

### ISSUE THREAD

**Issue by kswartz26** [veler/DevToys#131]
You have chosen to release this code using an MIT License. The license reads, in part:

> "Permission is hereby granted, free of charge, to any person obtaining a copy of this software ... to deal in the Software without restriction, including without limitation the rights to ... sublicense and/or sell copies of the Software."

But then you also write in the README:

> "I don't care if you copy the source code to use in your project, but please avoid simply changing the name and selling as your work without further change. That's not why I'm sharing the source code, at all."

That request is _contrary_ to the terms of the license. You can't offer the code under a license with a set of terms, then tell people you don't want them  to follow those terms.

If you do not want people to sell the code, please choose a different license. You may want to consider a CC-BY-NC license if you don't want someone to sell it. I'm not aware of any standard license, however, that prohibits someone from forking and renaming a project, without making changes.

**Comment by veler** [comment]
Hi,

Thanks for sharing this. I understand the confusion. Here is why I did this:
1. I'm OK if people want to use this app for commercial use.
2. I'm OK if people clone or fork this app. Also, I figured that a lot of people fork repositories to bookmark them instead of "star" them.
3. I'm OK if people fork the project, make significant changes (add features, change the behavior deeply, change the UI deeply) and then sell it under a different name.
4. What I'm not OK with is when people fork the project, change the name and icon and nothing else (so no added value from the original repo), and `sell` it.

Ultimately, I'd like to avoid a scenario like Captura: https://github.com/MathewSachin/Captura/issues/405#issuecomment-657065501

Unfortunately, I don't know any license that would prevent this.

What do you think about? Any idea of how we could change the license with respect of the above? Perhaps we should write a custom license? I think one of the challenges here is to define what is a `significant` change.

Thanks :)

**Comment by kswartz26** [comment]
Indeed, you're right. There is no OSI-approved license that would meet those conditions. There are some non-commercial licenses that would prevent someone from selling the code, but nothing that limits it to only forks where nothing is changed.

I think you really have two choices. One would be to create a custom license, that includes these terms. There are some drawbacks to this. Your license would no longer be recognized by GitHub, and it would no longer conform to an OSI-approved license, which could hinder its discovery and adoption in some places. Also, it would only apply to versions of code to which the new license is applied -- all the older versions can't be retroactively changed, so a really committed person could just fork the _older_ version and re-release. (They would not be able to backport changes made after the license change, though, since those changes are bound by the new license terms.) 

The other alternative is to change it from a requirement to a recommendation. I think it would perfectly reasonable to say "I'm using a license that permits redistribution and commercial use without changes, but I would really prefer you not, and if you believe you have a strong reason to do so, kindly reach out to discuss with me first." The problem is that you can't legally _enforce_ these restrictions with an MIT license (and it's even harder still to enforce a concept of "added value" - does obfuscating the code without making any changes provided added value?) But changing the wording gives you a chance to outline your concerns without appearing to contradict the license, and may even give you an opportunity to relicense the code for other purposes should the need arise.

**Comment by veler** [comment]
Hi @kswartz26 ,

These are great ideas, thank you for sharing!
After chatting with @btiteux , we believe your 2nd option might fit better for us.

I updated the README in the following PR: https://github.com/veler/DevToys/pull/133

Can you please let us know what you think about it?

Thank you so much for your help with this! We really appreciate :)

**Comment by kswartz26** [comment]
I think that looks great, and definitely resolves the conflict. Very glad this was helpful to you!

**Comment by veler** [comment]
Thank you very much! :D I will merge this change then.
