### ISSUE TITLE
SQL formatter

### ISSUE THREAD

**Issue by rlm96** [veler/DevToys#136]
**Is your feature request related to a problem? Please describe.**
As a software engineer, I use SQL formatter to make my queries more understandable. This can be done manually or using online tools but sometimes due to data restriction policies this is not possible.

**Describe the solution you'd like**
I think it would be a good idea to implement a SQL formatter.

**Describe alternatives you've considered**
Online tools such us https://www.dpriver.com/pp/sqlformat.htm or manually.

**Additional context**
N/A

**Comment by veler** [comment]
Hi,

I love this idea. :) Definitely something we can add! Thank you for suggesting this.
We're planning to release DevToys 1.0 in January. We frozen feature work to focus on translation and bug fixes at the moment. Once 1.0 is release, we can look at including the formatter.
Meanwhile, even if 1.0 isn't released yet, we can still commit to `main` branch, so feel free to contribute if you wish. Otherwise, we will look at implementing it in a few weeks probably.
Thank you again!

**Comment by veler** [comment]
This JavaScript library under MIT license seems to be one of the best open source SQL formatter out there.
https://github.com/zeroturnaround/sql-formatter

It may be interesting to make a fork of it in C#.

**Comment by vukovinski** [comment]
This one is build in WPF, and already used in files.community

https://github.com/QL-Win/QuickLook

**Comment by SamNHS** [comment]
I've tried the zeroturnaround formatter and it doesn't work so well with MSSQL, especially when using SQLCMD or @@
```sql
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "dbname"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
           BEGIN
     PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
   SET NOEXEC ON;
 END


GO
USE [$(DatabaseName)];

/* INSERT, ALTER transactions here */

IF @@ERROR <> 0
                  AND @@TRANCOUNT > 0
    BEGIN
  ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
     VALUES                 (1);
        BEGIN TRANSACTION;
  END


GO

IF EXISTS (SELECT * FROM #tmpErrors) ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT>0 BEGIN
PRINT N'The transacted portion of the database update succeeded.'
COMMIT TRANSACTION
END
ELSE PRINT N'The transacted portion of the database update failed.'
GO
DROP TABLE #tmpErrors
GO
PRINT N'Update complete.';


GO
```

**Comment by akarboush** [comment]
Hi @veler, I just noticed that you assigned the problem yourself, I would like to know if you already started working on it? 
Because I managed to get a C# fork of the JS library, and it works fine doing the job. It just needs more testing and some optimization could be done too in terms of memory as well. I already have a plan how to do it, but I just wanted to make sure it works at least.

**Comment by veler** [comment]
Hi @akarboush , I was actually working on it yesterday evening. The branch is here: https://github.com/veler/DevToys/tree/sqlformatter

It's pretty much done. At least it's working and unit tests are passing. However I did a literal translation from JS to C#, so as you mentioned, there's some optimization to do (for example, right now we create tons of instances of strings, which isn't optimal in C#).

Feel free to look at it and suggest some changes. :)

**Comment by akarboush** [comment]
Funny thing, I did work on it before yesterday too as an individual project (just pushed to my GitHub). I might also publish it as a NuGet package if I have the time to do so.

And Since you have already written the tests, I will take it as it is and start optimizing it as soon as I could
