### ISSUE TITLE
Extensibility for Third-Party Module/Tool 

### ISSUE THREAD

**Issue by expikr** [veler/DevToys#146]
**Is your feature request related to a problem? Please describe.**
Turning this into an ecosystem of simple jscalc-like applets ensures longevity and mindshare of the app as the centralized authority for swiss-army devtoys 
(potentially killing off all those random "converter websites" that you needed to google and pray it's legit)

**Describe the solution you'd like**
Establish an API/template format that lets people code and add simple tools to the main application, akin to JSCalc in terms of intentionally limited functionality to signal that this is only for a quick swiss-army knife task and not meant to be a "main" tool.

**Describe alternatives you've considered**
VSCode has tons of powerful extensions, but mentally I think of them more as a whole "workspace" for serious work, as opposed to disjointed "swiss army knife" utilities that I can quickly whip out then close immediately.

**Additional context**
To start maybe we can just allow importing of "modules". Perhaps far into the future it could be nice to have an in-app module-creator similar to JSCalc specifically for rapid creation of very simple functionalities, while module-importing maybe allows for somewhat more complex tools.

**Comment by veler** [comment]
Hello,

Thanks for sharing this feedback. This is a subject that @btiteux and I talked about recently. I will try to summarize what we talked about.

# Discussion outcome

1. DevToys initially has not been designed with third part extensibility in mind, although it has an internal extensibility system making all the tools being dynamically registered on launch.
2. While one of the big arguments for using DevToys is that it works entirely offline, we also believe that some people just don't care and would appreciate having, for example, a quick/minimalist REST Client. But we would lose the argument/credibility of being an offline app, which is a very key argument for using DevToys instead of any website out there.
3. Another thing that is an actual issue we're facing: PNG / JPEG Compressor. Currently, this tool requires a third part .exe to work. This makes DevToys requiring the `full resource access` permission.
![image](https://user-images.githubusercontent.com/3747805/150282101-6a298b9a-6980-46cb-a971-4524e0113b88.png)
While the app still doesn't use internet, this information displayed in the MS Store may make the user wonder why the app needs this permission.
Another tool we have in mind (on-screen color picker) will also require this permission.
4. Another issue we have: Windows 10/11's Roaming Settings are being deprecated (see #81). This is, personally, a feature that I LOVE because it's seamless, and unfortunately, to support it now, we would need to implement this ourselves and to add the `internet access` permission.
5. Therefore, the solution is to make these tools/feature optional by taking advantage of the UWP App Extension support. Users would be able to install the main DevToys app that has no permission, and later, install extensions that will add more tools, but will require permission (and of course we would make clear to the user that these extensions need extra permissions).
6. I already experimented this approach in the branch `extensibility`: https://github.com/veler/DevToys/tree/extensibility
7. It works great, but there's a ton missing. One of the biggest challenge is that UWP App Extension are working Out Of Process, meaning that the extension can't have a simple XAML for the UI and CS file for the code behind. What needs to be done is to make an SDK that would allow the extender to define the UI through an abstraction. For example, there would be a dummy "Button" class. When the extension sends this object to the main app, the main app will create a Button in the UI. All this increase the complexity, and since DevToys hasn't been designed with this approach in mind right at the beginning, we realized that taking this direction means that we should pretty much rewrite the app from scratch.

# Conclusion / TL;DR

To make third part extensions possible, we need to rewrite the app from scratch. Let's do that in a DevToys 2.0 maybe. We don't have any timeline for it. Unless we get a high demand for it, it will stay very low priority. :)

**Comment by veler** [comment]
Target for DevToys 2.0:

We may need to stick to UWP for Windows, with the opportunity of using .Net 6 on MacOS. UWP apps unfortunately have a very restricted way to extend an app through a plugin/module approach.
We may not make DevToys extensible in version 2.0, as long as we can't upgrade to WinUI 3.

As a reminder, we can't upgrade to WinUI 3 because WebView 2 in WASDK app doesn't support transparent background, which is a blocking issue for us as it prevents some important UI element such as Mica effect. See https://github.com/microsoft/microsoft-ui-xaml/issues/2992 and https://learn.microsoft.com/en-us/microsoft-edge/webview2/get-started/winui#transparency

**Comment by veler** [comment]
New finding, and update.

So we finally decided to ditch UWP support because making UWP and .NET 6/7 co-habit together was a mess. We're migrating to WinUI3. The advantages that .NET brings over UWP worth the lack of opacity on WebView.

Meanwhile, regarding the extensibility approach, we discovered something:
- In Apple world, Mac Catalyst doesn't support JIT on ARM64. As a consequence, we need to build using AOT. https://github.com/xamarin/xamarin-macios/issues/11724
- AOT has its own set of advantages and disadvantages. For example, it makes the app faster to start, and smaller on the hard drive. But, it also prevent us from loading assemblies at runtime. Therefore, it prevent us from being able to load a plugin at runtime.

It sounds like we may need to abandon completely the idea of an extensible app. It causes a bunch of question related to guarantee of privacy and safety anyway.
This is not a final decision but likely the road we will take.

**Comment by veler** [comment]
New update:

We figured out how to have extension support on Windows, Mac and Linux, including in ARM64. 😁

**Comment by veler** [comment]
Not yet, but we believe we took a good direction with the future API but we're still testing it before delivering anything. We will port all the existing tools before sharing any documentation, hoping for the API to get mature during this exercise.

**Comment by veler** [comment]
Extension manager added: https://github.com/veler/DevToys/pull/901
