### ISSUE TITLE
My IT Admins block Windows Store Access

### ISSUE THREAD

**Issue by scottwdavis** [veler/DevToys#192]
Is there any way to get a version of this app that I can install without having to go through the Windows Store? My IT admins have decided to 100% block the windows store. I tried downloading the v1 msixbundle release from github, but i was unable to complete the installation because it said it said:

"This app package is not signed with a trusted certificate. Contact your system administrator or the app developer to obtain a new certificate or app package with trusted certificates. The root certificate and all immediate certificates of the signature in the app package must be trusted (0x800B010A)"

**Comment by jwfxpr** [comment]
@scottwdavis, did you try to install the certificate, as mentioned in the second point [here](https://github.com/veler/DevToys/blob/main/README.md#Manual)?

>### Manual
>
>- Download and extract the latest release.
>- Install the certificate in Trusted Root.
>- Double click the *.msixbundle file.

The certificate in question can be found with the `.msixbundle` file in the release assets, with the file extension `.cer`. Try downloading that, right click the file and select "Install certificate", choose store location "Current User", "Place the certificates in the following store" and "Browse..." to select "Trusted Root Certificate Authorities", and proceed to the finish of the certificate installation wizard.

However, if that doesn't work due to your administrative restrictions, that's a different matter 😊

**Comment by Atrejoe** [comment]
Doesn't work for me (yet), are you sure that the certificate should be added to `Trusted Root Certificate Authorities` and not `Trusted Publishers`?

Sounds a bit risky to me.

**Comment by oxygen-dioxide** [comment]
You can try https://github.com/oxygen-dioxide/Zhihu-UWP/releases/download/v1/DevToys_1.0.0.0.Msixbundle

**Comment by ashemedai** [comment]
> Doesn't work for me (yet), are you sure that the certificate should be added to `Trusted Root Certificate Authorities` and not `Trusted Publishers`?
> 
> Sounds a bit risky to me.

Don't just add certificates to the Trusted Root Certificate Authorities. This is the basis for many certificate-based operations on your operating system. This means you trust the people who created the root certificate to never start issuing certificates for other purposes.

Heck, .NET even has warnings for this: https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca5380

**Comment by Atrejoe** [comment]
Why was this closed?
