### ISSUE TITLE
Why is this product not available on Mac?

### ISSUE THREAD

**Issue by CassySpencer** [veler/DevToys#203]
### What's the Problem?

There is absolutely no reason why this product is not available on Mac other than the fact Microsoft wants everyone to use windows, even though almost 100% of Silicon Valley uses Macs.

### Solution/Idea

Compile for Macs. This is obviously a web app with a browser shell. Therefore, you should be able to make it available on Apple Macs

### Alternatives

Make it available on Apple Mac. What more is there to say?

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by tpgionfriddo** [comment]
Hi Cassy, this is not a web app with a browser shell, if you look at the code you will see its written in entirely c# with the UWP, which works only on Windows.
See #156 for further discussion as to why DevToys is currently only available on Windows

**Comment by veler** [comment]
Hi Cassy,

> no reason why this product is not available on Mac other than the fact Microsoft wants everyone to use windows

First, this app isn't made by Microsoft. It's made by me a friend in our spare time. So saying that `Microsoft wants everyone to use windows` because this particular app isn't on Mac is wrong.

> This is obviously a web app with a browser shell.

No, it is not. This app is a UWP app. It is native 92% native code. Please [learn the difference between web app and UWP here](https://stackoverflow.com/questions/42292576/main-difference-between-a-web-application-and-windows-universal-application).
In addition to the fact that this is not a web application, there are many other reasons as mentioned here: https://github.com/veler/DevToys/issues/156#issuecomment-1018298004
