### ISSUE TITLE
DevToys not showing up in MS Store & MSI bundle description says "Uses all system resources" on the opening screen!

### ISSUE THREAD

**Issue by krabs-github** [veler/DevToys#208]
### Description

DevToys not showing up in MS Store & MSI bundle description says "Uses all system resources" on the opening screen!

Is this package safe to download and install from GitHub? Something seems wrong. Add to that, it doesn't show up in the MS Store has me very hesitant to install
![Screenshot 2022-01-23 062006](https://user-images.githubusercontent.com/78506543/150676000-4433c7f2-5600-4c3e-ab5a-49ab4c085cb4.png)
.

### Steps To Reproduce

1. Search MS Store for DevToys, Click on DevToys app.
2.  Run MSI Bundle and read the the description that says "Uses all system resources".

### Expected behavior

Appear in the MS Store & Not have a suspicious description in the MSI Bundle.

### DevToys Version

Version 1.0.0

### Relevant Assets/Logs

![Screenshot 2022-01-23 062006](https://user-images.githubusercontent.com/78506543/150676072-0cbbd541-d780-4638-b091-13047c07cf0f.png)

**Comment by krabs-github** [comment]
![Screenshot 2022-01-23 062006](https://user-images.githubusercontent.com/78506543/150676135-5edace9d-2d19-47bc-bbea-2fa94ffef0b9.png)
 Screenmshot of the Capabilities section stating "Uses all system resources"

**Comment by krabs-github** [comment]
This is a very strange capabilities message. Obviously I didn't install the root cert of an app that claims it is going to use all my system resources.

**Comment by btiteux** [comment]
Hello,

The question about the full trust permission is a good point we are going to update the readme to indicate why. 
The app need the full trust permission because we are using [ECT](https://github.com/fhanau/Efficient-Compression-Tool) to work with images.

For the store it's seems you have a problem (reference to the error code **0x00000005**), I found a post about this error that may help you [0x00000005](https://answers.microsoft.com/en-us/windows/forum/all/windows-store-error-0x00000005/c7fe788f-7339-49a8-ae6d-07042073e7ec).
You should be able to see the apps 
![image](https://user-images.githubusercontent.com/81378823/150691692-b9a83947-98ed-4e40-ae41-4fe1be74c62b.png)
