### ISSUE TITLE
Hope to add multilingual support

### ISSUE THREAD

**Issue by Gaoyifei1011** [veler/DevToys#29]
Thanks to the developers for their hard work. I really like this app, which currently offers some of the features that developers often use. At present, English, French and system default languages have been added to the Settings of this app. We hope to support more languages in the future design, such as simplified Chinese, traditional Chinese, Russian, Japanese, Korean and other languages used by the majority of people or other countries.

感谢开发者的辛勤付出。我非常喜欢这个应用，这个应用目前提供了开发者经常使用到的一些功能。目前这个应用已经在设置中添加了英语，法语和系统默认语言的选项，希望在未来的设计中能够支持更多的语言，例如简体中文，繁体中文，俄语，日语，韩语等其他国家或被大多数人使用的语言。

**Comment by vladimirkosolapov** [comment]
@veler, regarding this topic, I'd like to suggest a way to simplify further translation for contributors, which you could follow when adding new text strings.

For example, commit 4468b6ee93af225d99b6641f5edd302eff00729a added new text strings to the localization files, but only for "en" and "fr". Accordingly, if after some time I want to suggest an update for "ru" translation, I'll need to copy-paste these lines from "en" manually, which isn't very convenient and may be fraught with missing some lines due to inattention.

I suggest that when adding new text strings, you paste them into localization files of other languages as well, so that after a while the contributors can just open these files and translate the missing strings. This will add a little extra work for you, but also will make it easier to translate new strings. 😅
