### ISSUE TITLE
"Keep on top" window resizing is too restrictive

### ISSUE THREAD

**Issue by jwfxpr** [veler/DevToys#330]
### Description

Many DevToys tools have UIs that require a reasonably large window size to be usable. This makes them incompatible with the "Keep on top" option as it is currently implemented.

For example, comparing texts in normal mode:

![image](https://user-images.githubusercontent.com/20788820/152143762-db66bf4b-b41f-4e2d-b108-0aa3e92b155a.png)

The same but in "Keep on top" mode, with the window at the maximum allowed size:

![image](https://user-images.githubusercontent.com/20788820/152143850-d9eec1e2-c1b0-4fb3-a9b9-b2c891641b8b.png)

XML formatter:

![image](https://user-images.githubusercontent.com/20788820/152144348-dc1ce533-ce1b-4494-a0b3-cbb08e7ec2f0.png)

![image](https://user-images.githubusercontent.com/20788820/152144369-5e1eaf96-eecd-476f-b661-ab6af1f5ca5a.png)

If "Keep on top" is going to be a meaningful and usable interface option, it must allow for larger window sizes than it currently does.

### Steps To Reproduce

1. Open a tool with multiple large text controls.
2. Try to use "Keep on top".

### Expected behavior

Keep on top window resizing _should_ be less restricted.

Keep on top window resizing _could_ be completely unrestricted _iff_ there is a much stronger visual signal that keep on top mode is currently enabled. This will minimize the user confusion/frustration with a full-screen keep-on-top window that the current resizing limitation is designed to prevent.

### DevToys Version

Version 1.0.2.0 | X64 | RELEASE | b972462 | b972462

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/20788820/152143850-d9eec1e2-c1b0-4fb3-a9b9-b2c891641b8b.png)
![image](https://user-images.githubusercontent.com/20788820/152144369-5e1eaf96-eecd-476f-b661-ab6af1f5ca5a.png)

**Comment by veler** [comment]
Hi,

This is a fair comment, thanks for sharing :)

For background, the Top Most feature is part of what can be done with UWP SDK. Unfortunately this mode has a maximum size set by the system. That said, some improvement in the layout can definitely be done. For example, hidding some options and stacking the text editor vertically instead of horizontally so line of code are less short.

What do you think about?

**Comment by xeonmc** [comment]
seconded on automatically switching between horizontal and vertical stacking based on whether sufficient width exists for two minimum-width editors

**Comment by jwfxpr** [comment]
Adjusting the layout based on window width seems a good general UI enhancement, yes! 😊 I didn't realise that the UWP SDK was the limiter of the keep-on-top window size.

Since the code in the UWP SDK is out of scope, I'm going to suggest another approach which would be a more significant change.

**Firstly**: we can take direct control of the window position by interfacing directly with `user32.dll` and [`SetWindowPos()`](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setwindowpos), particularly the [`HWND_TOPMOST`](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setwindowpos#:~:text=A%20window%20can%20be%20made%20a%20topmost%20window%20either%20by%20setting%20the%20hWndInsertAfter%20parameter%20to%20HWND_TOPMOST%20and%20ensuring%20that%20the%20SWP_NOZORDER%20flag%20is%20not%20set) flag.

```csharp
const int HWND_TOPMOST = -1;
const int SWP_NOZORDER  = 0x004;

[DllImport("user32.dll", EntryPoint = "SetWindowPos")]
public static extern IntPtr SetWindowPos(IntPtr hWnd, int hWndInsertAfter, int x, int Y, int cx, int cy, int wFlags);
```

**Secondly**: I would suggest changing the semantics of the ![image](https://user-images.githubusercontent.com/20788820/152291993-3f67e1d5-b309-458d-89e0-1ef914976143.png) button. This symbol, to me, does not suggest "Keep on top", it suggests a breakout of the current tool to a new independent form. I would suggest that this is a more useful feature, allowing multiple forms with a separate tool in each. The keep on top function would still be available, but using a more familiar UI element such as a pin icon, adjacent to the breakout icon.

I realise that that's a much more ambitious enhancement, if you think it's worth considering I can create a new issue for creating new windows for tools. What do you think?

**Comment by veler** [comment]
Hello @jwfxpr ,
Thanks for sharing this.
To get a UWP app on top of every other windows (top most), we have to use the CompactOverlay feature of UWP Sdk.
https://docs.microsoft.com/en-us/archive/blogs/universal-windows-app-model/compactoverlay-mode-aka-picture-in-picture

This feature has limited options which help to enforce consistency across other UWP apps installed on the system. For example, every app going to CompactOverlay mode will be anchored to the top right of the screen and will have a small size (I think the maximum allowed is 500x500 px but can't find confirmation anywhere). The Movie & TV app (on W10), Calculator app, Fluent Screen Recorder and other apps support this feature.

![image](https://user-images.githubusercontent.com/3747805/152400583-a456df0e-5a54-4516-9c72-821182c0037b.png)

![image](https://user-images.githubusercontent.com/3747805/152400766-b550bcac-b0fd-48a6-bcca-58d1385ec4bb.png)

Keep in mind that in UWP, we can't use Win32 API like user32.dll. It's by design since UWP apps are running in a sandbox and have limited access to system resources (mostly for security purposes, like iOS and Android apps).

There is no other way to set a UWP window on Top Most than using the CompactOverlay mode.

In summary of above, the spirit behind the CompactOverlay feature is to anchor the app in the top-right corner of the screen and keep a small size so it doesn't hide most of the other windows on the screen. With that being said, I believe the icon of the button makes sense in this case. The arrow on the icon points to a smaller rectangle in the top-right corner, which summarizes the entire concept of this mode. Additionally, the icon is consistent with other apps providing this experience too.

I can see how a `pin` icon could also work, however `pin` can mean many other things like pinning the tool in the menu of the app, pin the app to the task bar, or even pinning the tool to the Start Menu of Windows, which is by the way supported by DevToys. I think the `pin` icon would be more confusing at this point.

![image](https://user-images.githubusercontent.com/3747805/152402598-d6cd9d9e-698f-44c5-bdf4-6b30eaa8a273.png)

![image](https://user-images.githubusercontent.com/3747805/152402627-04246f15-9c4b-43e1-a989-38f45dea0f56.png)

![image](https://user-images.githubusercontent.com/3747805/152402993-53abd92f-47c1-4e6d-b470-4b4edebf4c66.png)


In conclusion, while I do agree that the layout can and should be improved for some tools, I don't think we will be able to make the window larger when being Top Most, and the visual indication on the UI is consistent and makes sense in my opinion.

**Comment by jwfxpr** [comment]
Thanks for the thoughtful reply @veler! As you can see I'm not familiar with UWP, so thanks for the detailed explanation.

I also hadn't recognised the CompactOverlay icon from other apps, but now that you've mentioned it, yes, I've seen the same icon used for this feature in a handful of other apps.

I guess an automatic layout reflow with vertical stacking is the best strategy to make tools more usable in the CompactOverlay window!

**Comment by veler** [comment]
You're welcome :)

> I guess an automatic layout reflow with vertical stacking is the best strategy to make tools more usable in the CompactOverlay window!

Agreed! I marked this issue as part of the current milestone. Will try to improve it soonish. :)

**Comment by veler** [comment]
You're welcome :)

> I guess an automatic layout reflow with vertical stacking is the best strategy to make tools more usable in the CompactOverlay window!

Agreed! I marked this issue as part of the current milestone. Will try to improve it soonish. :)
