### ISSUE TITLE
Memory leak in SearchResults

### ISSUE THREAD

**Issue by niyari** [veler/DevToys#369]
### Description

If a collapsed tool panel is not expanded ~~If the tools that use MonacoEditor are not displayed beforehand~~, they will consume more memory.
Once all the tools are displayed, the memory consumption will slow down.

### Steps To Reproduce

1. Start DevToys.
2. Enter text into the tool's search (e.g. 0).
3. Press the Enter key several times.

### Expected behavior

Data used in the search is referenced only once.

### DevToys Version

Version 1.0.2.0 | X64 | RELEASE | b972462 | b972462

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/2970321/153501212-41430f4e-ac02-4c95-a041-06a6d6f007cd.png)

**Comment by veler** [comment]
@btiteux,
I investigated the bug and I think I have gone to the bottom of it. Here is what I found:
1. When we type a query in the search box and press [Enter], we navigate to a page by calling this method:
https://github.com/veler/DevToys/blob/aa8624afee5e55de1506d41180506d7ec59d64c8/src/dev/impl/DevToys/ViewModels/MainPageViewModel.cs#L440-L483
2. In this method, we change the selected item in the NavigationView and notify that the SelectedMenuItem property changed, so the NavigationView update with the selected item: https://github.com/veler/DevToys/blob/aa8624afee5e55de1506d41180506d7ec59d64c8/src/dev/impl/DevToys/ViewModels/MainPageViewModel.cs#L472-L472
3. By raising this property, some properties of `MatchedToolProvider` are being get because they're binded to some NavigationViewItem: https://github.com/veler/DevToys/blob/aa8624afee5e55de1506d41180506d7ec59d64c8/src/dev/impl/DevToys/Api/Tools/MatchedToolProvider.cs#L18-L153
4. Now here is the weirdness:
  * When all the groups in NavigationView are expanded, `MatchedToolProvider.Icon` is not called.
  * When all the groups in NavigationView are collapsed, `MatchedToolProvider.Icon` is called for each hidden item.
  * The impact of this is that we load some SVG, Font Glyph...etc. This is what allocates memory, and this is what explains the memory leak.

The proper fix in long term, in my opinion, is to continue our work on making all the tools icons a font. It likely cost less than our routine for loading the SVGs.
Additionally, we might need to open an issue on WinUI repository because it's quite obscur to me that this property is being called in this scenario.

**Comment by youkai95** [comment]
I was also looking at this issue and I found another problem here:
https://github.com/veler/DevToys/blob/aa8624afee5e55de1506d41180506d7ec59d64c8/src/dev/impl/DevToys/Core/ToolProviderFactory.cs#L38-L49

This caching is not working correctly. It seems like every time you start a new search, a new IToolProvider instance is created and passed to this method. When it tries to look for a match inside the dictionary, it never finds an usable ViewModel as the comparison is made by reference, hence the cache dictionary begins to fill with repeated ViewModels.

This only happens with SearchResultToolProvider, the other providers does not have this problem. I am not sure why...

**Comment by veler** [comment]
Good catch @youkai95 ! I just fixed it on my machine but it doesn't address the memory issue.
