### ISSUE TITLE
Number Base Converter - Custom base 

### ISSUE THREAD

**Issue by Andret2344** [veler/DevToys#384]
### Solution/Idea

Now number base formatter allows only converting between binary, octal, decimal and hexadecimal number bases. But It is possible to use different bases, e.g. 7, 3 or 12. How about allowing to decide about input and output number base for conversion by typing number between 1 (unary system) and (let's say) 36 (all uppercase alphanumerics).

### Alternatives

Using [this](https://www.rapidtables.com/convert/number/base-converter.html) website

### Priorities

| Capability | Priority |
| :---------- | :------- |
| Allow to choose input and output number base | Must |
| Properly handle negative numbers | Should |
| Have no upper limits of numbers | Could |
| Allow to add "another" row with different (or same...) number base output  | Could |

### DevToys Version

Version 1.0.3.0 | X64 | RELEASE | 7c7c02a | 7c7c02a

**Comment by youkai95** [comment]
I have something like this already done, @veler I would like to take this issue. Here are some interesting details like having a custom character dictionary to map the input to a custom base.

If you agree to implement this, I could have a fully working PR in a couple of days.

**Comment by Andret2344** [comment]
Glad to hear you want to implement this, @youkai95! Can you please, for clarity, share the UI you are going to implement, to be able to debate over it?

**Comment by youkai95** [comment]
@Andret2344 honestly I think it is time to remake this UI. Now with a custom base it would see too awkward with 4 fixed bases to convert and a text input accepting/showing the value converted to a custom base. 

With this feature an input for the base number will be needed, and we could accept another input for the conversion dictionary, if we want to. This could break the limit of the maximum base size. Anyways it is true that this UI could lack of UX if I just add a couple of fields for this... I am not sure about how to make this comfortable for the user, in addition to the fact that I am not very skilled with xaml UI designs. If you want to lend me a hand with this, I will gladly accept it!

(I could upload an image later with a mock if you wish, here are 3:30am)

**Comment by Andret2344** [comment]
Yes, just an image with placeholders would be great. 

I'm not skilled in C# at all, so I cannot offer any support, unfortunately.

**Comment by youkai95** [comment]
> Yes, just an image with placeholders would be great.
> 
> I'm not skilled in C# at all, so I cannot offer any support, unfortunately.

@Andret2344 Ok, no problem. Now I am going to sleep... In a while I will upload a mock of what I have already done.

**Comment by xeonmc** [comment]
Maybe some inspiration [here](https://github.com/veler/DevToys/issues/256#issuecomment-1021607956)

**Comment by youkai95** [comment]
Sorry for the delay, I had some affairs to attend. @Andret2344 this could be a mockup of how could we get things done. I tried to include all the possible features on it. 

This design could have a few problems, in example: the format option could lead to problems if we use custom base dictionaries as there could exist differences between characters case for the conversion. I could work on a dictionary input validation to accept formatting conversions, perhaps I dont feel like having this feature included...

Maybe we should discuss a bit more this feature before pushing a solution to the repo. Please, @veler I would like to have some considerations from you. I have already done the code to convert from/to a custom base using a custom dictionary, this is more a UX discussion.

This could be a mockup for this new changes, and if we accept to do something like this, I consider that my previous PR could be closed without merging it.
![base_converter_mockup](https://user-images.githubusercontent.com/14837216/154762972-f7decc67-fa19-432f-ac4e-7e576e29df17.png)

**Comment by Andret2344** [comment]
The UI is generally great, IMO. If it comes to the dictionary, In fact, the dictionary field could accept only uppercase letters, I mean changing the input case to upper case. Then `a` and `A` both will be `A`. Additionally, every char in the field must be unique.

The format option seems useless now, as there is no way of formatting a number of a base 7. On the other hand, converting to common base would be nice to have the output formatted.

@veler We would be really happy to hear your opinion and suggestions, because there are a few doubts

**Comment by xeonmc** [comment]
Why not leave the current UI as-is and add a collapsible section for "misc number bases" that include also other endian types, and among one of them could be "custom:"

**Comment by jwfxpr** [comment]
> Why not leave the current UI as-is and just Add an "Other Number Bases" collapsible section for things like different big/little endian types (and maybe signed unsigned etc) and among them could also be a more involved "custom" base one?

Yes, I agree with this. The current base converter UI works pretty well and covers the vast majority of use cases for the tool.

I also share @veler's curiosity about how important _aritrary_ bases and dictionaries are to our target users. I get that arbitrary bases are possible and arbitrary dictionaries are cool, but could you offer us a use case for, e.g., using a base 7 number system which would just be stored in 8 bits of memory anyway? Or storing numbers in arbitrary base encoding dictionaries? 🤔 Is there some obvious and important reason to use arbitrary bases and dictionaries that I'm missing here?

I suspect truly arbitrary number bases maybe belong in a hypothetical MathToys project, and our UI should be focused on the developer domain. Adding useful base dictionaries like those RFC4648 implementations, which are designed to minimise letter ambiguities like `0` `O`, etc, is far more useful to 99% of developers.

**Comment by jwfxpr** [comment]
Also, small point, there's no need for a field to enter the base for a custom dictionary. The length of the dictionary determines the base. 😊 `0123456` -> base 7, etc.

**Comment by Andret2344** [comment]
Hi all, thanks for taking part in the discussion. 

Reading all your comments, I must admit the UI is really simple and simple enough for most users and use cases and adding them custom base to choose would only confuse newbies etc. So how about creating a switch labeled as "advanced mode" that would replace the current simple UI with the advanced on suggested by @youkai95?

Now, answering the @veler's doubts, the custom base wouldn't be widely used as it's not generally needed, and we should keep the current simple UI. The reason why custom base is needed is quite simple: learning and teaching. At the university, we were obliged to convert number in base 23 to number in base 7, or from base 19 to base 9. The only way to verify it was to convert calculations to base 10. On the other hand, as I'm teaching the conversions, it'd be very handy to simple convert it.

**Comment by youkai95** [comment]
As @veler said, me neither had the need of converting a number to a base out of the common ones. I am not sure how much this change could be used, however as it is not something hard to do and there are people requesting it I decided to give it a try and look for a clean solution. 

Maybe completely change the UI could be challenging for some dev that are not adapted to work with that level of customization. Also, expose the digits dictionary it is more like an entertainment than a feature because many people could confuse or make a wrong use of it (in addition, I do not think that someone could go out of [0-9a-f]).

If you prefer I could make a PR only with functionalities and leave the UI design to other person. As @xeonmc said, we could use a collapsible section and leave this level of customization out of the common features. Or even we could give this a workaround and use a new section...

@jwfxpr what if I decide to use a personal numeric alphabet? Among all the weird things, this is a weirdest one, but ok... I could leave an open door for it XD Also, that accepts the possibility to change between different base64, base128 dictionaries as stated in RFC4648.

**Comment by xeonmc** [comment]
![image](https://user-images.githubusercontent.com/77922942/154815118-8509f003-e113-4d04-8daf-287d55a9293e.png)

**Comment by jwfxpr** [comment]
That seems like the best compromise to me, @xeonmc. Minimal clutter, and the flexibility's there for those who need it. I think a drop-down is a good way to fold them together, and leaves us room if for some reason we have reason to implement other number base standards in future👍

@Andret2344, @youkai95, thanks for engaging with us on this, it will be good to have the extra features implemented into the tool. 😊

For the "Custom base", I don't know of any standardized base alphabets beyond 64, so I think we should allow bases 2–64 and just use a basic `0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz+/` alphabet.

**Comment by Andret2344** [comment]
Just one question. How about allowing to add an extra line with another IO field? Something like this (with removing them as well... somehow)

![image](https://user-images.githubusercontent.com/40674613/154821431-7ae11f48-cc7a-4961-a122-139a74d37fd8.png)

**Comment by youkai95** [comment]
> How about allowing to add an extra line with another IO field?

Are you talking about allowing as many "Other" IOs as the user decides?

**Comment by Andret2344** [comment]
> > How about allowing to add an extra line with another IO field?
> 
> Are you talking about allowing as many "Other" IOs as the user decides?

yes, indeed

**Comment by xeonmc** [comment]
some refinement:
![image](https://user-images.githubusercontent.com/77922942/154822087-7f6d0d5c-50ad-443e-9233-fb6185061d5f.png)

**Comment by xeonmc** [comment]
I propose also adding a "Roman Numerals" base

**Comment by btiteux** [comment]
Hello,

I would prefer to keep the current UI for the "base" case and add a advanced mode switch. 

This way we could switch between base (current UI) and advance (new UI) and you can add all the fields you need without reducing the margin between them. 

The Advanced mode should be a new ViewModel and a new View. 

What do you think?

**Comment by Andret2344** [comment]
> Hello,
> 
> I would prefer to keep the current UI for the "base" case and add a advanced mode switch.
> 
> This way we could switch between base (current UI) and advance (new UI) and you can add all the fields you need without reducing the margin between them.
> 
> The Advanced mode should be a new ViewModel and a new View.
> 
> What do you think?

I suggested it a few comments above


> Hi all, thanks for taking part in the discussion.
> 
> Reading all your comments, I must admit the UI is really simple and simple enough for most users and use cases and adding them custom base to choose would only confuse newbies etc. So how about creating a switch labeled as "advanced mode" that would replace the current simple UI with the advanced on suggested by @youkai95?

And I agree it would also work, but the solution suggested by @xeonmc would also work. Now we only need to decide which solution is to be implemented. @veler, I guess your vote is deciding now

**Comment by btiteux** [comment]
Yes I know @Andret2344 just can quote on the mobile app don't know why 😁.

We need to check the render in compact mode too 🙂

**Comment by veler** [comment]
Hello,

Like @btiteux and @Andret2344 suggested, I'd also prefer a toggle switch that would enable an Advance mode where the UI could, if we want, completely different.

# UI

The default UI could like exactly like the current one, but with an extra option on the top:

![image](https://user-images.githubusercontent.com/3747805/154857837-f4bed721-366d-4347-9656-3152144d40cf.png)

Once "Advanced mode" is enabled, it could switch to a different UI like the following:

![image](https://user-images.githubusercontent.com/3747805/154857863-13661aa0-cc98-41f9-8e29-9ca6592ce591.png)

While I now do see the value for converting in more base than the 4 most we allowed by default, I'm still not convinced by the custom dictionary approach though. Except for study purposes, does anyone here ever need a custom dictionary of characters after doing a number base conversion?

**PS:** @youkai95 , what did you use to make your mock above? It looks nice. I used PowerPoint because I didn't feel like it worth using Figma, but your mockup look much fancier. 🤣

# Implementation

Because it would have a different UI with a different mechanism, I'd suggest splitting the UI into 3 different views.

* 1 User Control that would only have the `Advanced mode` and `Format number` options.
* 1 User Control for the `non-advanced` view, which would have the `Hexadecimal`, `Decimal`, `Octal` and `Binary` text boxes.
* 1 User Control for the `advanced` view, which would have the `Input base number` option, `Input`, `Output`...etc.

The last 2 User Control could be placed into a Border/Grid/ContentPresenter in the 1st one, and the `Advanced Mode` option would simply show one while hiding the other.

Each User Control should have its own View Model. The advanced and non-advanced User Control's View Model should be able to listen to the `Format Number` option so they react when the user interact with it. You can use Events or Messenger for this. Please put the common conversion logic into `NumberBaseHelper` and refactor whatever's needed to make both modes working smoothly without too much duplicated code. :)

Here is an example of how we send messages between View Models:

https://github.com/veler/DevToys/blob/07d84344352d2036fa1bd290607a4da444305c09/src/dev/impl/DevToys/ViewModels/Tools/GroupToolViewModelBase.cs#L25-L26

https://github.com/veler/DevToys/blob/07d84344352d2036fa1bd290607a4da444305c09/src/dev/impl/DevToys/ViewModels/Tools/GroupToolViewModelBase.cs#L36

https://github.com/veler/DevToys/blob/4cfcbbaf5004d61eca530791c6ce79653ffda86c/src/dev/impl/DevToys/ViewModels/MainPageViewModel.cs#L41

https://github.com/veler/DevToys/blob/4cfcbbaf5004d61eca530791c6ce79653ffda86c/src/dev/impl/DevToys/ViewModels/MainPageViewModel.cs#L371


What do you folks think about?

**Comment by xeonmc** [comment]
I feel like having a dropdown defaulting to Base-64 makes sense as a reasonable "fifth conversion". The user ignoring the dropdown and just doing his thing will just see it as yet another esoteric conversion. The user clicking on the dropdown out of curiosity will see all those options and, if he is confused, at least the burden of confusion has a cognitive cause-and-effect of "ok this dropdown is some weird stuff but I can just ignore it".

**Comment by Andret2344** [comment]
> # Implementation
> Because it would have a different UI with a different mechanism, I'd suggest splitting the UI into 3 different views.
> 
> * 1 User Control that would only have the `Advanced mode` and `Format number` options.
> * 1 User Control for the `non-advanced` view, which would have the `Hexadecimal`, `Decimal`, `Octal` and `Binary` text boxes.
> * 1 User Control for the `advanced` view, which would have the `Input base number` option, `Input`, `Output`...etc.
> 
> The last 2 User Control could be placed into a Border/Grid/ContentPresenter in the 1st one, and the `Advanced Mode` option would simply show one while hiding the other.
> 
> Each User Control should have its own View Model. The advanced and non-advanced User Control's View Model should be able to listen to the `Format Number` option so they react when the user interact with it. You can use Events or Messenger for this. Please put the common conversion logic into `NumberBaseHelper` and refactor whatever's needed to make both modes working smoothly without too much duplicated code. :)

@veler I'm not sure `Format number` should be a common part. Above we agreed that is quite hard to format number out of the set of standard bases, so I guess it should be a part of the `non-advanced` view.

**Comment by veler** [comment]
> @veler I'm not sure Format number should be a common part. Above we agreed that is quite hard to format number out of the set of standard bases, so I guess it should be a part of the non-advanced view.

Oh, you're correct! My bad!

**Comment by xeonmc** [comment]
Made a slightly different mockup:

![image](https://user-images.githubusercontent.com/77922942/154860473-28bf0c1f-21a2-47e2-a58c-288522e6e726.png)

**Comment by jwfxpr** [comment]
I have to say I prefer the simplicity of a single fifth field at the bottom, as in @xeonmc's mockups. It's simple, self-explanatory, and more flexible. I don't see an obvious place for the RFC4648 specs in the advanced mode option, for example. Adding other things later becomes a fresh debate over which view to alter in which way, versus just adding another option to the drop-down. 😊

Also, yeah, what are we all using for these mockups? I'm curious too 😆

**Comment by xeonmc** [comment]
MSPaint

**Comment by youkai95** [comment]
@veler a friend of mine shown me an app to make mockups and I just fallen in love with it. Its name is Balsamiq Mockups 3. I dont know if there is a new version but this one has everything needed for a good mockup. This app it is not free though...

If all of you agree I will just make a PR with the logic needed to convert from/to a custom base using a custom dict, then we could just use that logic in the way we think it will be the correct way. My point is to review the code while we decide how to use it. Later we could finish the PR with the UI we decide.

**Comment by veler** [comment]
Hi all,

@youkai95 , thanks for the tip!

@xeonmc , @jwfxpr , @youkai95 , @btiteux , I think you folks convinced me. I think I actually prefer's xeonmc approach here now. Sorry for the change of mind so quickly.

That said, I'm concern by how this field would look like when DevToys is in Compact Overlay mode
![image](https://user-images.githubusercontent.com/3747805/155006398-b3260856-3288-4677-aaef-b21bd2467582.png)

![image](https://user-images.githubusercontent.com/3747805/155006449-adab2d64-9853-40e0-a135-7cc3d188ddb5.png)

![image](https://user-images.githubusercontent.com/3747805/155006480-775fbc74-b08e-477a-996b-6a4ea712d99e.png)

I feel like the UI of this specific field will be too small (+ imagine if "Other" and "Custom Dictionary" are taking 2-3 times this space in some other languages).

While I'm pointing out this concern, I don't necessarily have a good answer to it right now. Have you folks thought about it already, and/or imagined a different layout that would work with a small UI like this?

**Comment by xeonmc** [comment]
The way it could be implemented is that there is always a persistent dictionary as a separate row atop the input, just that it is hidden unless the Custom Dictionary option is selected. Then all that happens when the user selects one of the preset dropdowns is changing the content of that persistent (but invisible) dictionary field. Likewise with the custom base input field, it is also persistent but only visible when the right dropdown is selected.

So the implementation logic would be something like
1. user selects a preset dropdown
2. the preset dropdown populates the persistent field with its associated dictionary
3. the base number is calculated from the populated dictionary field and updated
4. the visibility state of the two elements is updated based on the selected dropdown-option's associated config

**Comment by niyari** [comment]
Personally, I find the standard Windows calculator ( calc.exe ) to have the best UI.

[calculator](https://github.com/microsoft/calculator)
It has a simple UI, but also allows pasting and copying of values.
![image](https://user-images.githubusercontent.com/2970321/155174723-8b38591e-efe5-4d86-9e99-ddd901b40f31.png)

**Comment by btiteux** [comment]
The compact mode will be complicated.
I made these wireframe to test with an Advanced Mode

**Normal View**
![image](https://user-images.githubusercontent.com/81378823/155192282-20c51582-a374-41d0-9636-b8e3ff933a1a.png)
![image](https://user-images.githubusercontent.com/81378823/155192351-ee74c8f8-db97-4360-947d-490a0b42525a.png)

**Compact View**
![image](https://user-images.githubusercontent.com/81378823/155192480-d2a83f60-73a4-4894-a0b2-0a03ece1fad0.png)

We need to keep the UI consistent with the others tools. 

So if we made some changes on component for this tool we need to see the impact on the other tools too.

**Comment by Andret2344** [comment]
Personally, I really like the @btiteux's UI mockup and in fact I was thinking about something exactly like this. The consistency is a really important argument. This approach also keeps the UI not overcomplicated with huge amount of fields to set it up

**Comment by xeonmc** [comment]
![image](https://user-images.githubusercontent.com/77922942/155239984-a389a2ef-c358-438a-b748-f326fd38d3b5.png)

**Comment by niyari** [comment]
I wrote this code when I was interested in Base32, but there are several derivative versions of Base32.
https://github.com/niyari/base32-ts/blob/0cba699ea43986bc6cbab9558de8d08ffee413c8/src/base32.ts#L62

| Type | Dic | Comment |
| :---------- | :------- | :-- |
| RFC4648_HEX | '0123456789ABCDEFGHIJKLMNOPQRSTUV' |  |
| RFC3548 or RFC4648 | 'ABCDEFGHIJKLMNOPQRSTUVWXYZ234567' |  |
| Clockwork Base32 | '0123456789ABCDEFGHJKMNPQRSTVWXYZ' | 1 I i L l  = 1 |
| crockford | '0123456789ABCDEFGHJKMNPQRSTVWXYZ' | Perhaps the specifications only contain numerical values. |

**Comment by veler** [comment]
Hello,
Sorry for the late answer.
I also prefer the last @btiteux mock up. The consistency is good, it works well with the Compact Mode and the `Advanced` option allows most users to have a restricted; not confusing UI on first place.

@youkai95 , would you like to have fun implementing it? :)

**Comment by youkai95** [comment]
> @youkai95 , would you like to have fun implementing it? :)

@veler I could give it a try but I have few experience working with UWP (however seems to be very similar to WPF), so I am not sure about how to correctly face this UI. I will use your previous recommendation as a guide. 

I am pushing a draft PR (#430) for you to review what I have done at the moment while I begin with UI.

**Comment by veler** [comment]
Hello,

Sorry for the late answer again.
UWP UI is quite similar to WPF, indeed.
To implement it, you can create 2 new UserControls, as I mentioned above. At the end of the day, there would be 3 UserControls in the `Views\Tools\Converters\NumberBaseConverter` folder.

1. `NumberBaseConverterToolPage.xaml` => This one would contains the common UI to the 2 mode. In short, it would have the `Advanced mode` option.
2. `NumberBaseConverterSimpleView.xaml` => this one would have the current UI that we have in DevToys.
3. `NumberBaseConverterAdvancedView.xaml` => this one would have the new UI when Advanced Mode option is enabled.

The 2 new user controls can be placed in the UI of NumberBaseConverterToolPage. You can use some binding along with a [BooleanToVisibility](https://github.com/veler/DevToys/blob/8a17b71dc4cd2dae451056e3cd0e4617a04f4cbe/src/dev/impl/DevToys/UI/Converters/BooleanToVisibilityConverter.cs#L12-L55) converter to show/hide `NumberBaseConverterSimpleView` or `NumberBaseConverterAdvancedView` based on the value of `Advanced mode` option. There are plenty of placed where we use `BooleanToVisibility` in the solution. :)

Let me know if this help. :)
