### ISSUE TITLE
JWT Decoder improvement

### ISSUE THREAD

**Issue by veler** [veler/DevToys#39]
**Is your feature request related to a problem? Please describe.**
JWT Decoder is out, that's great! :D 
But it lacks a bit of color and easy to read data.

**Describe the solution you'd like**
Let's try to make it even better by humanizing some data like the date/time and apply a specific syntax colorization to it.

**Comment by KillyMXI** [comment]
Another improvement suggestion:
Mention the full name (JSON Web Token) somewhere on the page.
I first found this abbreviation when tried DevToys - it doesn't seem a common knowledge yet.

**Comment by jplandry908** [comment]
It would be great if:
- you could create a JWT token from the header and signature (and not just the other way around)
- you could verify the JWT signature is valid 

This site has similar functionality for reference: https://jwt.io

**Comment by KyleKorndoerfer** [comment]
One thing that jumped out to me when using the JWT Decoder is that the header & payload panels are equally sized. Rarely do I find that the header information exceeds the payload so it would be nice to either:
- apply different proportions to these panels
- allow the panels to be resized/collapsed so that I can focus on whatever is important at the time, which is almost always the payload
