### ISSUE TITLE
Escape tool escapes new-lines as '\r'

### ISSUE THREAD

**Issue by ShlomiAltostra** [veler/DevToys#468]
### Description

The escape tool escapes new-lines as `\r`s

### Steps To Reproduce

Go to 'Text Escape / Unescape'
Make sure it's in "Escape" mode
Insert inputs which include a few lines of text

The 'Output' now has `\r` instead of `\n`s (or `\r\n`, though preferably just `\n`) instead of line breaks

### Expected behavior

New llines should be escaped as `\n` a line-feed character instead of a carriage-return

### DevToys Version

1.0.5.0

### Relevant Assets/Logs

![image](https://user-images.githubusercontent.com/57314279/160353913-f5b9b4b3-9c9e-4cca-bb18-aa6d3883c766.png)

**Comment by veler** [comment]
Hello,
Thanks for your feedback.
This actually makes me wonder: perhaps we need an option allowing to select whether the return carrier character should be `\n`, `\r` or `\r\n`. What do you think?

Ping @btiteux and @rlm96 too.

**Comment by rlm96** [comment]
I think that's a good idea, that way we can just switch the carrier character.

**Comment by AHeiming** [comment]
Hi,
if this is okay for you, it would like to try solving this, though it's the first time I'm working with .xaml files and a Microsoft Store App 😅 

I hope that's okay for you.

**Comment by AHeiming** [comment]
![image](https://user-images.githubusercontent.com/44135066/176504903-5dc5e695-5c0a-4b50-86d8-72d601096818.png)

This is how I thought it should look.
Icon is just temporary, any suggestions on the icon?

**Comment by veler** [comment]
Hey @AHeiming , thanks for your suggestion.
I like this idea. Here is a suggestion to make it (hopefully) even better:
1. Instead of using some Radio Button, use a Combo Box, like for the option in `JSON Formatter`.
2. Instead of just displaying `\r`, `\n`, `\r\n`, show `CRLF (\r\n) (Windows)`, `CR (\r) (Mac)` and `LF (\n) (Linux)`.

Quick question:
Is that something that currently work on your machine or is this just a mock up?
Please feel free to open a PR (even draft). We can iterate on it together 😊

Thank you !

**Comment by AHeiming** [comment]
Hi,

thanks for your suggestions! This is currently working on my machine, but not finished yet.
I hope to get this done this weekend.

I have a question, why a Combo Box? Should it behaive like a Radio Button? Because a multi selection does not seem working here for me.

**Comment by veler** [comment]
Hi,

That would be wonderful :D 

I suggest a Combo Box just so it's consistent with other tools offering options with multiple choice, like these:

![image](https://user-images.githubusercontent.com/3747805/178119656-87116d26-a4a0-4a6b-8c7a-77f36296bf18.png)

![image](https://user-images.githubusercontent.com/3747805/178119669-7a76b6f8-985b-46d6-a5b5-77f68a1875ef.png)

![image](https://user-images.githubusercontent.com/3747805/178119675-77553578-6bdc-46a1-b558-8f310c154d69.png)

Please let me know if I can be of any help :)

**Comment by AHeiming** [comment]
Thanks @veler, I'm looking forward to implement this the way you suggested next week 😄

**Comment by jai-dewani** [comment]
Hey @AHeiming are you still working on this or can I give this a try?

**Comment by AHeiming** [comment]
Hi, 

I have currently no time to work on this, so sure, give it a try!

**Comment by minhaz1217** [comment]
@veler , can I give this a try please?

**Comment by fbtwitter** [comment]
is there any update for this @AHeiming ?

**Comment by heribertolugo** [comment]
i've just finished this, since the previous person went awol.

i have a question before i commit, is it customary for the one implementing a feature to design the icon? or does the designer generally handle that?
and i only put a localization string for us-EN, because it is the only one i know. how is this typically handled?

**Comment by heribertolugo** [comment]
i cant push. i'm getting 403-forbidden error.

**Comment by heribertolugo** [comment]
i just submitted PR. i forgot to mention this issue in the PR.

![image](https://github.com/heribertolugo/DevToys/assets/26213368/c20122b5-2609-482a-9337-c9123f7b090f)
