### ISSUE TITLE
Unix Timestamp Converter - Timezone select

### ISSUE THREAD

**Issue by Andret2344** [veler/DevToys#473]
### Solution/Idea

When using timestamp converter, the date and time fields shows correct result, but doesn't allow me to change the time zone. It only takes the UTC (one of timezones) and my current (CEST). 
![image](https://user-images.githubusercontent.com/40674613/160441269-43efbb60-14b4-4c3d-8aae-baf9f6c2b400.png)

### Alternatives

I must change my PC timezone.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| Allow to choose timezone | Must |
| Merge two existing datetime rows into one with timezone select | Should |
| Have a possibility to add another row with another timezone | Could |
| Force me to use my current timezone (maybe as a default only) | Won't |

### DevToys Version

Version 1.0.5.0 | X64 | RELEASE | 99757dc | 99757dc

**Comment by niyari** [comment]
(WIP)
![image](https://user-images.githubusercontent.com/2970321/161846204-bcca1549-1dd1-480a-8531-38ea10fae034.png)

**Comment by Andret2344** [comment]
Looks really great! I have just a few suggestions:
* What's the point of leaving UTC, if it's one of the timezones?
* How about adding (where exist) named timezones in curly brackets (I.e. GMT, CET, UTC, PST etc.)? It'd look like `+01:00 (CET)` and `+02:00 (CEST)`.

**Comment by niyari** [comment]
> What's the point of leaving UTC, if it's one of timezones?

As I was updating this tool, I realized that the feature users want is "time conversion between two time zones."
For example, I have a scenario where I receive an email about a domain (e.g. .io ) and I want to compare Japan (+0900 JST) with the British Indian Ocean Territory (+0600).

![image](https://user-images.githubusercontent.com/2970321/161914756-b04d99cd-4a99-4843-a699-6577db1c6a61.png)
[TimeZonesMap - Wikipedia](https://upload.wikimedia.org/wikipedia/commons/8/88/World_Time_Zones_Map.png)

I think a better tool would be to set `Zone 1` to UTC and `Zone 2` to LocalTime as default values, and allow users to select any time zone.

> How about adding (where exist) named timezones in curly brackets (I.e. GMT, CET, UTC, PST etc.)? It'd look like +01:00 (CET) and +02:00 (CEST).

![image](https://user-images.githubusercontent.com/2970321/161916040-de7cdab3-350e-4333-8ab0-34b86ed3baf8.png)
Since the data exceeds 100, it is necessary to be able to retrieve as much information as possible from the OS and to support more ambiguous input.
![image](https://user-images.githubusercontent.com/2970321/161918020-4db3e7b5-3f0c-4a73-94ff-d27658bb97f4.png)

**Comment by niyari** [comment]
(WIP)
![image](https://user-images.githubusercontent.com/2970321/162606465-e34fccf1-a144-4f4f-803a-f96b83c18f11.png)
TimeZoneInfo

**Comment by niyari** [comment]
@Andret2344 How about this?
![image](https://user-images.githubusercontent.com/2970321/163050991-6442b570-e740-40c9-9c6d-84f5e6f2839f.png)

- Use time zone.
- Daylight saving time can also be calculated.

![image](https://user-images.githubusercontent.com/2970321/163051210-f449e3a7-0417-4db5-b656-824a01b0a238.png)
1520751599

![image](https://user-images.githubusercontent.com/2970321/163051371-817d6679-fe9b-445d-ab47-cf4d7516cb62.png)
1520751600

![image](https://user-images.githubusercontent.com/2970321/163052389-980a9869-658d-446a-8999-8ee8e6dbf2d8.png)
Invalid value.


> How about adding (where exist) named timezones in curly brackets (I.e. GMT, CET, UTC, PST etc.)? It'd look like +01:00 (CET) and +02:00 (CEST).

I can't think of a good way to do this at the moment, so it looks like we will have to choose from a list.

**Comment by Andret2344** [comment]
I think it's awesome! I think it's really perfect!

> I can't think of a good way to do this at the moment, so it looks like we will have to choose from a list.

Totally agree, I just thought about `+02:00 (CET)`, `+08:00 (PST)`, `+00:00 (UTC)` etc., but current solution with longer names are even better.

**Comment by niyari** [comment]
@veler How does it look?
We will be modifying and organizing the experimental implementation before making the pull request, which will take some time.

**Comment by veler** [comment]
Hello @niyari and @Andret2344 ,

So sorry for the late answer.
I like the idea of being able to convert the timezone when parsing a timestamp. I can see some scenario where it's very useful, for example, when dealing with date / time displayed at the local time in a website but that this same date / time is stored in UTC on a database and that you (the developer) is on a different timezone than the customer (so different "local time").

Anyway :)

I like the last mock that @niyari made. A couple of precision though:

1. Let's put the Timestamp field to the left and the Timezone field to the right.
2. Let's make sure we keep the Copy and Paste buttons near the Timestamp field.
3. (Open question) For ease of use, I wonder if it would make sense to have an item "Local timezone" in the drop down list and select it by default.
4. Change `Zone 1` text to `Output`.

What do you think? @niyari , feel free to work on it if you wish.

Thanks again for these great ideas and your patience with my late answers.

**Comment by niyari** [comment]
Current screenshot. (WIP)
![image](https://user-images.githubusercontent.com/2970321/163693133-9ecd0c98-8481-48fe-b189-df485f8b9bd7.png)
- The elements are close together so that the copy and paste buttons are recognizable as those used for timestamps.
- Initial state is `TimeZoneInfo.Local`. That is, the time zone set by the OS is selected.
- Ambiguous time period is being handled and how it is displayed is being investigated.

![image](https://user-images.githubusercontent.com/2970321/163693307-d8bf68e5-5404-4445-8091-ca1bc6da3cfb.png)

![image](https://user-images.githubusercontent.com/2970321/163693314-992f179e-8c10-4652-a899-bbea9046dad0.png)

Explanation by tooltip. (Copy and paste buttons. and DST.)
![image](https://user-images.githubusercontent.com/2970321/163693491-029830ea-b086-4e8c-b7ac-fec65640cc5b.png)

**Comment by veler** [comment]
Thanks for sharing this!

What about putting the Copy and Paste buttons above the Timestamp input so it's consistent with the other tools?
Regarding Daylight Saving thing, it that a button or just an indication? This UI is confusing me a bit. I can tell it's something about day time saving but can't tell what it indicates exactly.

If it's a button / switch, I'd suggest to make an option like in other tools.
If it's just an indication, I'd suggest to make it a bigger UI with clear textual explanation without having to put the mice on it to see the tooltip.
