### ISSUE TITLE
Text case converter and inspector only shows 12108 lines when pasting a really long string

### ISSUE THREAD

**Issue by DavidCZ2051** [veler/DevToys#494]
### Description

The "Text case converter and inspector" only shows 12108 lines but still counts the information right when pasting a long string.

### Steps To Reproduce

1. Go to the "Text case converter and inspector".
2. Paste in a long string that has over 12108 lines.
3. Wait for it to process.

### Expected behavior

Should show all the lines pasted by the user.

### DevToys Version

Version 1.0.6.0 | X64 | RELEASE | c032ebb | c032ebb

### Relevant Assets/Logs

![screenshot](https://user-images.githubusercontent.com/84991177/163591638-636aba29-7f7a-4a06-9c45-774be246c907.png)

**Comment by L1nu5** [comment]
I'll start working on this one.

**Comment by L1nu5** [comment]
I think there is another issue here- DevToys is frozen for the entire duration of the copy paste of such huge text data. I noticed that memory usage is well beyond 1GB. For me, I could not use DevToys after pasting the text and here are the statistics of the loaded text

![image](https://user-images.githubusercontent.com/14090904/163658205-4af9057e-e778-4b92-9c74-be6ae1729959.png)

![image](https://user-images.githubusercontent.com/14090904/163657993-259f1432-c33a-4f59-aac6-896122bfb51d.png)

I could think of two ways to fix this, but this could be a new feature itself:
1. Have a file open dialog like feature instead of having to copy/paste this much text data (optional)
2. Show a dialog box with a progress bar and a cancel button when data is being copied to the text input

**Comment by niyari** [comment]
This phenomenon is related to the `CustomTextBox` drawing process.
Issue #275 was (temporarily) solved by setting the output to a maximum of 10,000 lines.

**Comment by veler** [comment]
Yeah, it's unfortunately a known limitation of UWP's TextBox :( It doesn't scale well with very large texts... Code Editor (precisely the monaco-editor used in DevToys) has a better tolerance, but as you likely noticed, it takes about 1 second to load on each tool. If we use it on absolutely every tool, I'd find it a bit sad.

I guess another possibility is to re-implement ourselves a fully functional text box, but that's a very long and challenging work actually.

As of today, I don't have an ideal solution to bring. The best is likely the Code Editor, but again, not ideal...

**Comment by veler** [comment]
Fixed in DevToys 2.0
