### ISSUE TITLE
Feature Idea: JSON Diff

### ISSUE THREAD

**Issue by rdavison** [veler/DevToys#569]
### What's the Problem?

It would be nice to be able to do a diff of json data. 

### Solution/Idea

Something similar to http://jsondiff.com/

### Alternatives

I've tried http://jsondiff.com/ which I pasted above, and I have also tried some command line based tools.

### Priorities

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

### DevToys Version

0.0.10 macos

**Comment by veler** [comment]
Hello,

Thanks for the suggestion. 
On the Windows app, you can already do this by first using the JSON Formatter (if you need to un-minify a JSON, for example), then using the Text Diff tool.

![image](https://user-images.githubusercontent.com/3747805/177925883-915869d7-456b-493b-9747-c970b84f10c8.png)

![image](https://user-images.githubusercontent.com/3747805/177925948-d332c650-e5e6-400a-be93-b2a80282a40e.png)

I see that you mentioned you're using a MacOS app. Please note that this repository is only for the **_original_** DevToys app for Windows and that all the app with the same name (and sometime logo) on other platforms are clones that we do not own, don't maintain and aren't responsible for issues encountered with.

I'd be curious to know what app you're using though. :)

Thanks !

**Comment by rdavison** [comment]
@veler : Hi, yes, that's actually a great question... I didn't realize they were actually unrelated repos. The app I'm using is https://github.com/ObuchiYuki/DevToysMac

As for the workaround you presented, that's actually a great idea. Does the json formatter also sort the fields in an object? That's really the only thing it would need to do in order for a text-based diff to work consistently.

**Comment by veler** [comment]
@rdavison Sorting like this? :D 

![image](https://user-images.githubusercontent.com/3747805/178118533-c087e18f-3608-4c77-8d05-c1dd527db558.png)

I just added it following your comment ;-)
Pull request is available here: https://github.com/veler/DevToys/pull/578

It will be available in the next update for Windows. I have no idea if @ObuchiYuki will update his app. It looks like it's been a while the repository hasn't change and DevToys for Windows keep going its way without waiting for porting on other platforms (since we're not officially support them).
