### ISSUE TITLE
When any of the functional screens is opened, there is a single background load

### ISSUE THREAD

**Issue by NikolayEKolev** [veler/DevToys#649]
### Description

I'm not sure if it's a bug or architecturally designed that way. 
When any of the functional screens is opened, there is a single background load in the text boxes. I've stopped **Smart detection**, but it doesn't have any effect.

### Steps To Reproduce

1. Go to Text Comparer, XML Validator, XML Formatter, SQL, JSON...
2. The text boxes show some loading

### Expected behavior

Functionality to be initialized immediately.

### DevToys Version

Version 1.0.9.0 | X64 | RELEASE | 8bcfa60 | 8bcfa60

### Relevant Assets/Logs

https://user-images.githubusercontent.com/70388317/187275759-b3e52780-cbc1-4362-bed1-782e22a2336e.mp4

**Comment by veler** [comment]
Hello,

The current behavior is correct. The technical reason for this is that tools like SQL Formatter use the [Monaco text editor](https://microsoft.github.io/monaco-editor/), which enables line numbers and syntax highlighting. It is the same text editor than `Visual Studio Code`. We decided to use this one because it's commonly known by developers along with being one of the rare components giving us all these features for free (in the meaning that it was cheaper to do than creating our own code editor).

The drawback of this choice is that the editor lives in a web view. The reason why it takes some time to load the text editor is simply because it takes some time to load the page.

In the long term, we'd prefer using a more native text editor that doesn't require us to use a web view in the app. But we're not there yet. 😅
