### ISSUE TITLE
Update Microsoft store ratings image

### ISSUE THREAD

**Issue by 3kh0** [veler/DevToys#657]
Here is one I got from a screenshot that you can use, taken at 9/7/2022

![image](https://user-images.githubusercontent.com/58097612/189016368-efb79189-8c8a-4a1f-88ae-45c9ee7470c2.png)

**Comment by veler** [comment]
Hello,

The Microsoft Store, for some reason that I don't know, only shows reviews for the current country your Windows is associated to (I believe USA in this case). So, the 288 reviews are only made by people in USA. The screenshot I have on the README is from the Microsoft Partner Center, which is the portal that allows me to manage the app on the store and look at all the reviews in the world (not only a specific country).

Here are the global reviews. As you can see, there are 1.4k+, which I think is better to show in the README than the reviews from a specific country:
![image](https://user-images.githubusercontent.com/3747805/189162732-e13b2438-3919-466e-a1a7-5ffec30475ef.png)

# Off-topic

## Side-rant:
This mechanism from the Microsoft Store also mean that if in a specific country (let's say Country A), one of the early adopter shared a bad review (1 star for example), but that in every other countries the app gets great reviews, then the amount of download of the app may get screwed in Country A for a long time because people may perceive the app as a bad one that shouldn't be installed.

## KPI

While we're talking about reviews and acquisitions, for whoever is interested, here are some stats about the app:

### Acquisition
![image](https://user-images.githubusercontent.com/3747805/189164273-d140a57b-f5c5-40ad-8600-126080bf0ebb.png)

![image](https://user-images.githubusercontent.com/3747805/189164225-3df28d64-09e4-4ae6-8443-7d16d93016d1.png)

### Daily usage
It's funny how we can clearly see a drop over the weekend, which makes sense since it's a productivity app.
![image](https://user-images.githubusercontent.com/3747805/189165495-071f642e-c939-4e4a-8075-b127ef42af21.png)

### Retention
![image](https://user-images.githubusercontent.com/3747805/189164595-01bb366d-10b8-44e2-8c6f-631d180288c1.png)

### Engagement
One to two minutes is very short, but it makes sense since it's the kind of app people open spontaneously to do a short task (format a JSON, decode a text...) and close it as soon as they're done.
![image](https://user-images.githubusercontent.com/3747805/189164777-d2a4d6d6-6089-4a12-a358-d7cd25f10e05.png)

**Comment by 3kh0** [comment]
Thank you so much for this, I didn't even know about that, I left my good review and the app is just *chef's kiss* Thanks!
