### ISSUE TITLE
DevToys shouldn't register itself as a file picker

### ISSUE THREAD

**Issue by JaiganeshKumaran** [veler/DevToys#746]
<img width="1049" alt="Screenshot 2023-01-22 at 14 06 34" src="https://user-images.githubusercontent.com/45227503/213907245-cc8bf0a9-9111-4e3b-86f9-0648f5bdd941.png">

Remove from the manifest:
```xml
<uap:Extension Category="windows.fileOpenPicker">
    <uap:FileOpenPicker>
        <uap:SupportedFileTypes>
            <uap:SupportsAnyFileType/>
        </uap:SupportedFileTypes>
    </uap:FileOpenPicker>
</uap:Extension>
```

**Comment by veler** [comment]
Hello,

Thanks for your feedback. This is required in order to allow customers to open any kind of file in the app using this kind of button that you find at multiple places in the app. Not sure if I can workaround that.

![image](https://user-images.githubusercontent.com/3747805/213979654-5fbd8011-0731-45fa-a358-e6394fc668b2.png)

**Comment by Jaiganeshkumaran** [comment]
> Hello,
> 
> Thanks for your feedback. This is required in order to allow customers to open any kind of file in the app using this kind of button that you find at multiple places in the app. Not sure if I can workaround that.
> 
> ![image](https://user-images.githubusercontent.com/3747805/213979654-5fbd8011-0731-45fa-a358-e6394fc668b2.png)

For that, you can just add "*" as a file type filter.

**Comment by BreeceW** [comment]
@veler I believe you are confusing the FileOpenPicker API with the Windows extension. The FileOpenPicker API that you are using throughout the app allows users to pick any file because you have correctly set FileOpenPicker.FileTypeFilter.Add("*").

Totally unrelated, the Windows extension exists so when users open a file picker from another app, they can select an app as if it were a folder and the app provides a file. Declaring `<uap:SupportsAnyFileType />` is saying that DevToys should show up as a picker for every type of file in other UWP apps. But DevToys is not a picker (and so it should not declare that it is) and does not even implement the extension despite the declaration, so it just opens as a dead splash screen for every file type.

#747 should be merged. Users will still be able to open any file in DevToys, and they won’t see a broken DevToys entry cluttering other file pickers.

As you can see, any kind of file can still be opened in DevToys without that declaration.
![File open picker open in DevToys with the diff showing the extension in the manifest deleted and all files still being an option](https://user-images.githubusercontent.com/18747724/227108517-2a3c7596-df1d-402e-a0db-4a10814fdf37.png)
