### ISSUE TITLE
Reverse button in the Text Case Converter and Inspector tool has the same result as the Reverse alphabetize.

### ISSUE THREAD

**Issue by niyari** [veler/DevToys#850]
### Current behavior

Same result as reverse alphabetization.

### How to reproduce it (as minimally and precisely as possible)

test data
> 1 a 2
3 b 4
5 c 6
7 d 8
9 e 0
a j 1
b i 3
c h 5
d g 7
e f 9

1. Reverse alphabetize
2. Reverse

### Expected behavior

Each press of the button reverses the line.

### Affected DevToys kind

DevToys (app with GUI)

### DevToys Version

Version 1.0.9.0 | X64 | DEBUG | main | 56be3370

**Comment by veler** [comment]
Hi,

What you see is the expected result. In this specific scenario, the alphabetical reverse of the test data is the same thing that the reverse of the test data.

@micahmo , perhaps the term `reverse` is confusing? I admit I can't think of anything better for now though.

**Comment by micahmo** [comment]
I agree, this is working as designed. Maybe @niyari is expecting the contents of each line to be reversed (i.e., at the character level)? I tried to make it clear that all of the new operations were on a per-line bases with the "Sort Lines" heading. Of course, I'm open to ideas for improving clarity!

**Comment by micahmo** [comment]
Hi @niyari, now I understand what you're expecting, thank you for explaining.

On the one hand, I think this is implemented in accordance with the other operations on the page. They are one-way, and if you want to undo the operation, you can press "Original text".

On the other hand, the reason the above is true is because because most of the operations are idempotent. Reverse is not, and you could make an argument that, like Randomize, it should always operate on the current text rather than the original.

I guess I don't have a strong opinion here and will defer to the maintainer or others' opinions.

**Comment by veler** [comment]
I think I prefer the way it is currently: doing an operation based on the original text and not what's currently in the text box. Let's keep an eye opened for further feedback though.
