### ISSUE TITLE
Using Base64 Text feature on light theme crashes the application

### ISSUE THREAD

**Issue by eduxsan** [veler/DevToys#855]
### Current behavior

When a user goes to Encoders/Decoders > Base64 Text and Light theme is set, application crashes 

### How to reproduce it (as minimally and precisely as possible)

1. Open the app
2. Go to Settings > App Theme, set Light
3. Go to Encoders / Decoders > Base64

### Expected behavior

User should be able to use Base64 no matter what theme is enabled or if smart detection is disabled

### Workaround

Use dark theme

### Affected platforms

Windows

### Affected DevToys kind

DevToys (app with GUI)

### DevToys Version

Version 1.0.12.0 | X64 | RELEASE | 94bb8213 | 94bb8213

### Relevant Assets/Logs

[logs.txt](https://github.com/veler/DevToys/files/11710534/logs.txt)

**Comment by veler** [comment]
Duplicate with #755

**Comment by samysousa** [comment]
This one seems to be coming back. Regression ? 

The previous tickets talk about light theme but my repro step with latest `Version 1.0.13.0 | X64 | RELEASE | 2706c6c2 | 2706c6c2`

Reset and Uninstall application. 
Reinstall (Just to make sure nothing of the original app is still there). 

Works fine. 

Take any Base 64 Text, it is autodetected because "Smart Detection" is ON by default. 
Switch to Dark Theme (other cases say Light theme, but for me it's switching to Dark theme) and it crashes.
Restarting App, Crashes.
Never able to restart app until i perform another "Reset" app (In Apps control panel of Windows) 
Using Windows 10 X64 22H2 19045.3271
