### ISSUE TITLE
Allow for third-party plugins to be loaded into DevToys

### ISSUE THREAD

**Issue by EricWu91** [veler/DevToys#915]
### What feature or new tool do you think should be added to DevToys?

Allow for custom-written dlls to be loaded into DevToys and expand the amount of features available.

### Why do you think this is needed?

That allows for devs to centralize their self-written, specialized codes into a single platform. 

If an optional marketplace were to exist, these libraries could be shared with a larger audience, and further expand the amount of tools available.

### Solution/Idea

The implementation could be fairly simple. 

1. Create a new abstract class (or interface) representing the structure a would-be plugin should be created against:

This class would require a plugin-writer to provide basic data, such as Name, description and GUID, along with delegate implementations that would be called in specific points in the DevToys lifetime.

```c#
 public abstract class DevToolsPluginBase 
{
	public abstract string Name{get; set;}
	public abstract string ShortDescription{get; set;}
	public abstract string LongDescription{get; set;}
	public abstract string Guid{get; set;}

  // .. Other mandatory data
	public delegate void OnClick (object state); 
	public delegate void OnLoad (object state);

	public virtual OnLoad OnClick {get;set;}	 // Event called when the plugin icon is clicked 
	public virtual OnLoad OnLoad {get;set;}	 // Event called when the plugin finishes loading
}
``` 

2. A simple reflection could be used to list the dlls in a previously-provided path, and dynamically load them, provided they contain  type(s) that inherit from the abstract class above.

### Comments

Although my experience with WFM is limited, I've done this implementation before in a number of applications, so I'd love to help!

**Comment by veler** [comment]
Hi,

Thanks for suggesting this. Here are some great news:

1. We're working on DevToys 2.0
2. This new version will support extensions
3. You can see a preview of our Extension Manager in this pull request: https://github.com/veler/DevToys/pull/901
4. Every tools in DevToys 2.0 are extensions
5. We will have an API for it. There will be a documentation. The API is still having some breaking changes at the moment, which is why we do not invite people to try to make extensions for now.
6. In a few months from now, when we will have a Preview release for DevToys 2.0, we will publish a documentation and invite people to make extensions if they wish.

Hope this help :)

**Comment by veler** [comment]
Duplicate with #146
