### ISSUE TITLE
Add an RGB/Hex color picker

### ISSUE THREAD

**Issue by veler** [veler/DevToys#93]
**Is your feature request related to a problem? Please describe.**
As a user who works with colors, I need an easy to use, yet powerful RGB/Hex color picker.

**Describe the solution you'd like**
We can add through one or several tools:
- An in-app RGB/Hex color picker.
    - User should be able to save a color they picked so he can retrieve it after restarting the app.
- An on-screen color picker to pick up any color on the screen.
    - User should be able to save a color they picked so he can retrieve it after restarting the app.
- A color palette generator that would
    - Generate N random (or coherent) set of colors
    - Allow the user to lock the colors and generate others
    - Allow the user to re-order them
    - Allow the user to use a color picker to change them
    - Allow the user to save and copy the palettes.
 - A color contrast analyzer

**Technical Aspect**
- In-app color picker: WinUI has a color picker control we can use: https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.controls.colorpicker?view=winui-2.7
![image](https://user-images.githubusercontent.com/3747805/145079435-7e445a76-3e3f-4da3-99fd-3db743d55c33.png)

- On screen color picker: Perhaps we can take example on this app: https://www.microsoft.com/store/productId/9NTSZW9K2KG7 https://github.com/FireCubeStudios/fluent-rooler-demo , which is a fork of https://github.com/peteblois/rooler .

- For the palette generator, we can take example on this tool: https://coolors.co/faf3dd-c8d5b9-8fc0a9-68b0ab-4a7c59

- Here is an example of what a color contrast analyzer looks like: https://www.w3docs.com/tools/color-analyzer

**Comment by Arlodotexe** [comment]
Just throwing this in here
https://color.adobe.com/create/color-wheel

**Comment by KillyMXI** [comment]
https://github.com/microsoft/PowerToys has an on-screen color picker which can serve as an example for picks history. And for different color formats.

For in-app color selector control:

- Individual sliders are easy. Even gradients updated in real-time, while possibly non-trivial, still have a clear expected behavior (see Paint.NET or any graphics editor with sliders);
- once you attempt to make a single control to select a color you're going to have fun with 2d sliders for different color formats. There are many ways to combine three dimensions and none is universal. It's a UX challenge, and probably the only place to find serious attempts to address it are professional graphic editors - Photoshop and maybe couple others.

Why I'm looking for a good in-app color manipulation tool - sometimes I have an RGB or even single decimal color value and I need to produce lighter/darker color. So I want to be able to:

- paste a color in any format I have;
- switch to HSL (not HSV!!!, but some other more complex color models might be helpful since HSL has it's own limitations);
- copy the result color in the format to be used where needed.

Other notes:

- HTML hex colors can be long and short (2 or 1 hex digit per color);
- hex colors can have # in front of them;
- there is Alpha channel sometimes;
- hex and single decimal can potentially be arranged differently (RGBA, ARGB).

**Comment by xeonmc** [comment]
Would also be nice to lookup HTML color names and vice versa

**Comment by jwfxpr** [comment]
As mentioned above, this functionality is already well implemented and developed in other tools like PowerToys. Is there really a need to duplicate functionality from tools that most of us are already using? Does implementing this in DevToys offer an advantage over other color pickers that are readily available and well made?

**Comment by KillyMXI** [comment]
PowerToys doesn't do what I need though.

When I need to pick a color from screen, weirdly enough, I prefer to <key>Alt</key>+<key>PrnScr</key>, Paste to Paint.NET and have the screenshot around to pick different things. (Why using a boring list of colors when one can have a reference image as a palette. It automatically keeps context for every color.)

PowerToys don't allow to modify the color. Paint.NET only has HSV and the developer is too busy with the internals to look at the color window or any other UX things.

I often had to google "HSL online" and use that horrible page that does what I need (move that Lightness slider) but in rather unpleasing way. Every time I think I should probably make my own, but then I'm not using it frequently enough to bother.

Now I went to AlternativeTo.net to look for decent color pickers.
I think this one is pretty cool: https://alternativeto.net/software/free-color-picker/about/ ( GitHub https://github.com/jackdp/Free-Color-Picker )
Albeit it feels somewhat over-engineered, while missing on obvious relevant features (it has a gradient tool which doesn't specify in what color space the gradient is generated...).

There is still a room for a better, more convenient tool.
For DevToys it's just a matter of defining the scope - what is a "good-enough" tool to have in a swiss army knife to cover most use cases.
I wouldn't bother to keep specialized tools if it can do just what I need.

**Comment by xeonmc** [comment]
Maybe this could be combined with the colourblindness simulator to make a more generalized "color visibility analyzer"?
