### ISSUE TITLE
DevToys unresponsive on large texts

### ISSUE THREAD

**Issue by DanAvni** [veler/DevToys#953]
I have a gzip of a long text, when trying to use the gzip tool, DevToys becomes unresponsive for a while until the text is displayed on the output textbox. The issue is also happening if trying to paste the long text on the input textbox.

Version 1.0.13.0 | X64 | RELEASE | 2706c6c2 | 2706c6c2

**Comment by veler** [comment]
Hello,

This is a known limitation of DevToys 1.0. It's supposed to be fixed in DevToys 2.0.
Just to double check, would it be possible for you to share with me a sample of this large gzip or large text you're trying to paste, just so I can confirm how DevToys 2.0 (currently in development) behaves with it?

Thanks

**Comment by DanAvni** [comment]
@veler , I cannot share the document but it was very long (Probably at least a few MB). Take a Lorem Ipsum text of 3MB and you should probably see it (Just tested here and there things definitly stop responding for a while).

**Comment by veler** [comment]
Thanks! I tried a 10 MB file and it's almost instantaneous in DevToys 2.0 🤩
I will close this issue therefore 🙂
